In [1]:
import pandas as pd
from scipy import stats

In [2]:
education_districtwise = pd.read_csv('C:\\Users\\hp\\Desktop\\PYTHON\\Stat\\Day 3\\education_districtwise.csv')
education_districtwise = education_districtwise.dropna()    #used to remove missing values from a DataFrame

In [3]:
education_districtwise

,AC_YEAR,STATCD,DISTCD,STATNAME,DISTNAME,DISTRICTS,BLOCKS,VILLAGES,CLUSTERS,TOTPOPULAT,...,UUNI_ALL,UUNI_SC,UUNI_ST,TOTCLS1G,TOTCLS2G,TOTCLS3G,TOTCLS4G,TOTCLS5G,TOTCLS6G,TOTCLS7G
0,2015-16,1,101,JAMMU & KASHMIR,KUPWARA,1,13,391,104,875564.0,...,21322,26,2594,3489,5315,27,62,23,852,239
1,2015-16,1,102,JAMMU & KASHMIR,BARAMULA,1,18,678,144,1015503.0,...,17307,0,1571,4127,5800,210,53,30,1665,360
2,2015-16,1,103,JAMMU & KASHMIR,SRINAGAR,1,8,94,65,1269751.0,...,5444,31,408,817,3284,886,11,0,2873,40
3,2015-16,1,104,JAMMU & KASHMIR,BADGAM,1,13,523,104,735753.0,...,12469,18,857,2290,3837,119,45,8,1035,325
4,2015-16,1,105,JAMMU & KASHMIR,PULWAMA,1,8,359,64,570060.0,...,7408,17,855,1688,2584,151,67,5,1101,209
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
675,2015-16,36,3606,TELANGANA,RANGA REDDY,1,37,876,137,5296396.0,...,93203,25534,9457,7224,8298,529,0,121,15458,3337
676,2015-16,36,3607,TELANGANA,MAHBUBNAGAR,1,64,1458,230,4042191.0,...,134277,31001,14590,8936,7007,179,0,44,3730,3327
677,2015-16,36,3608,TELANGANA,NALGONDA,1,59,1117,216,3483648.0,...,96804,26577,14015,7592,4534,103,0,208,4026,3049
678,2015-16,36,3609,TELANGANA,WARANGAL,1,51,993,211,3522644.0,...,92224,23172,23525,6674,4677,153,0,207,7035,3060
679,2015-16,36,3610,TELANGANA,KHAMMAM,1,41,783,185,2798214.0,...,70234,15593,25217,6047,4015,104,0,32,3103,2228

In [13]:
state21 = education_districtwise[education_districtwise['STATCD']== 21]
state21

,AC_YEAR,STATCD,DISTCD,STATNAME,DISTNAME,DISTRICTS,BLOCKS,VILLAGES,CLUSTERS,TOTPOPULAT,...,UUNI_ALL,UUNI_SC,UUNI_ST,TOTCLS1G,TOTCLS2G,TOTCLS3G,TOTCLS4G,TOTCLS5G,TOTCLS6G,TOTCLS7G
392,2015-16,21,2104,ODISHA,DEOGARH,1,4,491,51,312164.0,...,11455,2358,4790,1056,1132,0,133,1,63,134
393,2015-16,21,2105,ODISHA,SUNDERGARH,1,21,1594,222,2080664.0,...,67129,8010,44194,5545,4700,359,502,45,875,684
394,2015-16,21,2106,ODISHA,KEONJHAR,1,17,1857,191,1802777.0,...,64157,8087,34183,4457,4284,85,724,29,577,901
395,2015-16,21,2107,ODISHA,MAYURBHANJ,1,30,3238,384,2513895.0,...,105772,8515,68723,7762,6804,16,729,15,510,1236
396,2015-16,21,2108,ODISHA,BALASORE,1,16,1830,207,2317419.0,...,73952,19493,11347,5252,4762,30,1074,0,179,1054
397,2015-16,21,2109,ODISHA,BHADRAK,1,9,1094,124,439917.0,...,52827,16958,2020,3632,3423,0,443,3,217,625
398,2015-16,21,2110,ODISHA,KENDRAPARA,1,11,1238,152,1439891.0,...,46863,13897,493,3400,3614,0,525,6,153,851
399,2015-16,21,2111,ODISHA,JAGATSINGHPUR,1,11,1051,130,1136604.0,...,29370,10398,472,3190,3319,45,445,0,227,519
400,2015-16,21,2112,ODISHA,CUTTACK,1,19,1515,214,2618708.0,...,63528,18563,5016,5195,5710,116,602,6,726,1002
401,2015-16,21,2113,ODISHA,JAJPUR,1,12,1448,152,1826275.0,...,59442,18971,6456,4093,4699,16,655,12,325,905
402,2015-16,21,2114,ODISHA,DHENKANAL,1,12,913,140,1192948.0,...,41954,11099,8208,2554,3453,16,393,6,170,397
403,2015-16,21,2115,ODISHA,ANGUL,1,11,1220,134,1271703.0,...,42554,10929,9147,2941,3499,232,286,6,355,758
404,2015-16,21,2116,ODISHA,NAYAGARH,1,10,1024,103,962215.0,...,35150,6592,3222,2290,2465,0,310,3,260,318
405,2015-16,21,2117,ODISHA,KHORDHA,1,15,1097,182,2246341.0,...,53386,11983,4938,3571,5009,723,484,32,942,882
406,2015-16,21,2118,ODISHA,PURI,1,15,1295,192,1697983.0,...,49890,13629,466,3576,3482,102,680,12,240,1053
407,2015-16,21,2119,ODISHA,GANJAM,1,40,2460,338,3520151.0,...,129249,35352,6309,7451,7941,239,571,7,1459,1122
408,2015-16,21,2120,ODISHA,GAJAPATI,1,9,1179,133,575880.0,...,24222,1835,15739,1843,2361,48,39,7,593,186
409,2015-16,21,2121,ODISHA,KANDHAMAL,1,14,1584,167,731952.0,...,38117,8227,21583,2991,3481,12,82,8,500,293
410,2015-16,21,2122,ODISHA,BOUDH,1,4,762,61,1506522.0,...,22442,6010,3139,1298,1379,14,98,6,70,113
411,2015-16,21,2123,ODISHA,SONEPUR,1,9,746,94,652107.0,...,22513,7224,2749,1449,1770,0,182,9,181,239
412,2015-16,21,2124,ODISHA,BOLANGIR,1,19,1774,209,1648574.0,...,68011,14022,17192,3372,4337,68,369,6,559,560
413,2015-16,21,2125,ODISHA,NUAPADA,1,8,627,87,606490.0,...,31704,4630,12876,1547,2270,16,164,3,201,169
414,2015-16,21,2126,ODISHA,KALAHANDI,1,17,1641,210,1573054.0,...,65781,15701,21833,4317,3836,58,369,9,619,428
415,2015-16,21,2127,ODISHA,RAYAGADA,1,14,1843,182,961959.0,...,36453,7768,21489,3520,3000,62,77,16,701,239
416,2015-16,21,2128,ODISHA,NABARANGPUR,1,12,870,166,1218762.0,...,63080,10921,37749,2985,3048,16,88,24,714,265
417,2015-16,21,2129,ODISHA,KORAPUT,1,18,1585,179,1376934.0,...,41134,8491,22539,4056,3544,104,111,14,947,437
418,2015-16,21,2130,ODISHA,MALKANGIRI,1,9,790,110,612727.0,...,27601,9004,15270,1903,1977,0,42,23,428,172

In [14]:
state28 = education_districtwise[education_districtwise['STATCD']== 28]
state28

,AC_YEAR,STATCD,DISTCD,STATNAME,DISTNAME,DISTRICTS,BLOCKS,VILLAGES,CLUSTERS,TOTPOPULAT,...,UUNI_ALL,UUNI_SC,UUNI_ST,TOTCLS1G,TOTCLS2G,TOTCLS3G,TOTCLS4G,TOTCLS5G,TOTCLS6G,TOTCLS7G
569,2015-16,28,2811,ANDHRA PRADESH,SRIKAKULAM,1,38,1521,397,2699471.0,...,122192,11629,8268,6529,5112,108,0,81,808,2927
570,2015-16,28,2812,ANDHRA PRADESH,VIZIANAGARAM,1,34,1366,243,2342868.0,...,102118,11300,12049,6420,2998,116,0,82,404,2667
571,2015-16,28,2813,ANDHRA PRADESH,VISAKHAPATNAM,1,43,2197,332,4288113.0,...,189510,15259,30353,9630,5585,394,0,36,2806,4070
572,2015-16,28,2814,ANDHRA PRADESH,EAST GODAVARI,1,64,1447,445,5151549.0,...,228385,45867,15508,12728,7358,111,0,28,1380,6014
573,2015-16,28,2815,ANDHRA PRADESH,WEST GODAVARI,1,48,871,367,3934782.0,...,167351,39731,6083,8276,5606,224,0,8,1144,4650
574,2015-16,28,2816,ANDHRA PRADESH,KRISHNA,1,50,927,414,4529009.0,...,178658,43255,6866,9280,6067,76,2,22,1814,5478
575,2015-16,28,2817,ANDHRA PRADESH,GUNTUR,1,57,718,378,4889230.0,...,0,0,0,9826,5817,103,0,66,3231,4085
576,2015-16,28,2818,ANDHRA PRADESH,PRAKASAM,1,56,957,371,3392764.0,...,142212,38109,5679,9379,4401,104,0,57,690,4180
577,2015-16,28,2819,ANDHRA PRADESH,NELLORE,1,46,1044,307,2966082.0,...,118739,30759,10280,8707,3791,143,0,53,210,4322
578,2015-16,28,2820,ANDHRA PRADESH,Kadapa,1,51,835,381,2884524.0,...,125329,24259,3680,9077,3807,92,2,59,419,4829
579,2015-16,28,2821,ANDHRA PRADESH,KURNOOL,1,54,904,308,4046601.0,...,188984,40360,4961,11072,7440,109,0,204,276,4927
580,2015-16,28,2822,ANDHRA PRADESH,ANANTAPUR,1,63,916,565,4083315.0,...,172577,30347,7656,10681,6172,120,0,178,144,5381
581,2015-16,28,2823,ANDHRA PRADESH,CHITTOOR,1,66,1372,568,4170468.0,...,176560,37082,8458,13082,4576,135,0,97,305,6771

In [15]:
#sample size n=20
#choose True cuz sampling with replacement replace=True
#choose arbitary number for random seed random_state=13450

sampled_state21 = state21.sample( n=20, replace=True, random_state=200)
sampled_state21

,AC_YEAR,STATCD,DISTCD,STATNAME,DISTNAME,DISTRICTS,BLOCKS,VILLAGES,CLUSTERS,TOTPOPULAT,...,UUNI_ALL,UUNI_SC,UUNI_ST,TOTCLS1G,TOTCLS2G,TOTCLS3G,TOTCLS4G,TOTCLS5G,TOTCLS6G,TOTCLS7G
418,2015-16,21,2130,ODISHA,MALKANGIRI,1,9,790,110,612727.0,...,27601,9004,15270,1903,1977,0,42,23,428,172
401,2015-16,21,2113,ODISHA,JAJPUR,1,12,1448,152,1826275.0,...,59442,18971,6456,4093,4699,16,655,12,325,905
408,2015-16,21,2120,ODISHA,GAJAPATI,1,9,1179,133,575880.0,...,24222,1835,15739,1843,2361,48,39,7,593,186
396,2015-16,21,2108,ODISHA,BALASORE,1,16,1830,207,2317419.0,...,73952,19493,11347,5252,4762,30,1074,0,179,1054
402,2015-16,21,2114,ODISHA,DHENKANAL,1,12,913,140,1192948.0,...,41954,11099,8208,2554,3453,16,393,6,170,397
415,2015-16,21,2127,ODISHA,RAYAGADA,1,14,1843,182,961959.0,...,36453,7768,21489,3520,3000,62,77,16,701,239
404,2015-16,21,2116,ODISHA,NAYAGARH,1,10,1024,103,962215.0,...,35150,6592,3222,2290,2465,0,310,3,260,318
407,2015-16,21,2119,ODISHA,GANJAM,1,40,2460,338,3520151.0,...,129249,35352,6309,7451,7941,239,571,7,1459,1122
417,2015-16,21,2129,ODISHA,KORAPUT,1,18,1585,179,1376934.0,...,41134,8491,22539,4056,3544,104,111,14,947,437
406,2015-16,21,2118,ODISHA,PURI,1,15,1295,192,1697983.0,...,49890,13629,466,3576,3482,102,680,12,240,1053
417,2015-16,21,2129,ODISHA,KORAPUT,1,18,1585,179,1376934.0,...,41134,8491,22539,4056,3544,104,111,14,947,437
417,2015-16,21,2129,ODISHA,KORAPUT,1,18,1585,179,1376934.0,...,41134,8491,22539,4056,3544,104,111,14,947,437
403,2015-16,21,2115,ODISHA,ANGUL,1,11,1220,134,1271703.0,...,42554,10929,9147,2941,3499,232,286,6,355,758
398,2015-16,21,2110,ODISHA,KENDRAPARA,1,11,1238,152,1439891.0,...,46863,13897,493,3400,3614,0,525,6,153,851
402,2015-16,21,2114,ODISHA,DHENKANAL,1,12,913,140,1192948.0,...,41954,11099,8208,2554,3453,16,393,6,170,397
416,2015-16,21,2128,ODISHA,NABARANGPUR,1,12,870,166,1218762.0,...,63080,10921,37749,2985,3048,16,88,24,714,265
393,2015-16,21,2105,ODISHA,SUNDERGARH,1,21,1594,222,2080664.0,...,67129,8010,44194,5545,4700,359,502,45,875,684
399,2015-16,21,2111,ODISHA,JAGATSINGHPUR,1,11,1051,130,1136604.0,...,29370,10398,472,3190,3319,45,445,0,227,519
411,2015-16,21,2123,ODISHA,SONEPUR,1,9,746,94,652107.0,...,22513,7224,2749,1449,1770,0,182,9,181,239
401,2015-16,21,2113,ODISHA,JAJPUR,1,12,1448,152,1826275.0,...,59442,18971,6456,4093,4699,16,655,12,325,905

In [12]:
sampled_state28 = state28.sample( n=20, replace=True, random_state=210)
sampled_state28

,AC_YEAR,STATCD,DISTCD,STATNAME,DISTNAME,DISTRICTS,BLOCKS,VILLAGES,CLUSTERS,TOTPOPULAT,...,UUNI_ALL,UUNI_SC,UUNI_ST,TOTCLS1G,TOTCLS2G,TOTCLS3G,TOTCLS4G,TOTCLS5G,TOTCLS6G,TOTCLS7G
579,2015-16,28,2821,ANDHRA PRADESH,KURNOOL,1,54,904,308,4046601.0,...,188984,40360,4961,11072,7440,109,0,204,276,4927
576,2015-16,28,2818,ANDHRA PRADESH,PRAKASAM,1,56,957,371,3392764.0,...,142212,38109,5679,9379,4401,104,0,57,690,4180
581,2015-16,28,2823,ANDHRA PRADESH,CHITTOOR,1,66,1372,568,4170468.0,...,176560,37082,8458,13082,4576,135,0,97,305,6771
574,2015-16,28,2816,ANDHRA PRADESH,KRISHNA,1,50,927,414,4529009.0,...,178658,43255,6866,9280,6067,76,2,22,1814,5478
575,2015-16,28,2817,ANDHRA PRADESH,GUNTUR,1,57,718,378,4889230.0,...,0,0,0,9826,5817,103,0,66,3231,4085
573,2015-16,28,2815,ANDHRA PRADESH,WEST GODAVARI,1,48,871,367,3934782.0,...,167351,39731,6083,8276,5606,224,0,8,1144,4650
576,2015-16,28,2818,ANDHRA PRADESH,PRAKASAM,1,56,957,371,3392764.0,...,142212,38109,5679,9379,4401,104,0,57,690,4180
575,2015-16,28,2817,ANDHRA PRADESH,GUNTUR,1,57,718,378,4889230.0,...,0,0,0,9826,5817,103,0,66,3231,4085
570,2015-16,28,2812,ANDHRA PRADESH,VIZIANAGARAM,1,34,1366,243,2342868.0,...,102118,11300,12049,6420,2998,116,0,82,404,2667
576,2015-16,28,2818,ANDHRA PRADESH,PRAKASAM,1,56,957,371,3392764.0,...,142212,38109,5679,9379,4401,104,0,57,690,4180
573,2015-16,28,2815,ANDHRA PRADESH,WEST GODAVARI,1,48,871,367,3934782.0,...,167351,39731,6083,8276,5606,224,0,8,1144,4650
575,2015-16,28,2817,ANDHRA PRADESH,GUNTUR,1,57,718,378,4889230.0,...,0,0,0,9826,5817,103,0,66,3231,4085
572,2015-16,28,2814,ANDHRA PRADESH,EAST GODAVARI,1,64,1447,445,5151549.0,...,228385,45867,15508,12728,7358,111,0,28,1380,6014
573,2015-16,28,2815,ANDHRA PRADESH,WEST GODAVARI,1,48,871,367,3934782.0,...,167351,39731,6083,8276,5606,224,0,8,1144,4650
580,2015-16,28,2822,ANDHRA PRADESH,ANANTAPUR,1,63,916,565,4083315.0,...,172577,30347,7656,10681,6172,120,0,178,144,5381
578,2015-16,28,2820,ANDHRA PRADESH,Kadapa,1,51,835,381,2884524.0,...,125329,24259,3680,9077,3807,92,2,59,419,4829
573,2015-16,28,2815,ANDHRA PRADESH,WEST GODAVARI,1,48,871,367,3934782.0,...,167351,39731,6083,8276,5606,224,0,8,1144,4650
577,2015-16,28,2819,ANDHRA PRADESH,NELLORE,1,46,1044,307,2966082.0,...,118739,30759,10280,8707,3791,143,0,53,210,4322
575,2015-16,28,2817,ANDHRA PRADESH,GUNTUR,1,57,718,378,4889230.0,...,0,0,0,9826,5817,103,0,66,3231,4085
572,2015-16,28,2814,ANDHRA PRADESH,EAST GODAVARI,1,64,1447,445,5151549.0,...,228385,45867,15508,12728,7358,111,0,28,1380,6014

In [16]:
sampled_state21['OVERALL_LI'].mean()

69.49100000000001

In [17]:
sampled_state28['OVERALL_LI'].mean()

68.5595

CONDUCT HYPOTHESIS TEST

1. state null and alternative hypothesis
2. choose significance level
3. find p-value
4. reject or fail to reject null hypothesis

In [20]:
stats.ttest_ind(a= sampled_state21['OVERALL_LI'], b= sampled_state28['OVERALL_LI'], equal_var=False)   #equal_var set to false cuz we dont want to assume two sample having same variance

TtestResult(statistic=0.26640970739657105, pvalue=0.7923141887098746, df=22.838750251057807)

In [ ]:
#t value is statistic=0.2664...... 
#p value 0.792... 79.2% which is more than 5% is null hypothesis